name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      working-directory: ./stm_rust_test
      run: rustup install thumbv7em-none-eabihf
    - name: Build
      working-directory: ./stm_rust_test
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      working-directory: ./stm_rust_test
      run: rustup install thumbv7em-none-eabihf
    - name: Test
      working-directory: ./stm_rust_test
      run: cargo test --verbose
