name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Update Rustup
      working-directory: ./stm_rust_test
      run: rustup toolchain install nightly --allow-downgrade --profile minimal --component clippy | rustup update
    - name: Setup Default
      working-directory: ./stm_rust_test
      run: rustup default nightly
    - name: Install Board Package
      working-directory: ./stm_rust_test
      run: rustup install thumbv7em-none-eabihf

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./stm_rust_test
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    
    steps:
    - uses: actions/checkout@v3
    - name: Test
      working-directory: ./stm_rust_test
      run: cargo test --verbose
